### ISSUE TITLE
Second level cache doesn't work with hibernate-core:5.4.0.Final

### ISSUE THREAD

**Issue by Fynjy** [grails/gorm-hibernate5#166] opened 2020-01-07 22:12 UTC
see HHH-11356 - Adjust the 2nd-Cache SPIs to better reflect supported uses (https://github.com/hibernate/hibernate-orm/commit/f432ecea687ce606144c8fca1f4fc7f1937e1c2a#diff-25149e72a238495de6c6d0c7c83be334)

In org.hibernate.metamodel.internal.MetamodelImpl.primeSecondLevelCacheRegions
was added check for isCached flag

`
if ( bootEntityDescriptor.isCached() ) {
// config cache region
}
`

org.grails.orm.hibernate.cfg.GrailsDomainBinder doesn't set isCached flag, but set CacheConcurrencyStrategy only.

**Comment by graemerocher** [comment] 2020-01-08 08:22
Thanks for looking into the cause, would you consider submitting a PR?

**Comment by longwa** [comment] 2020-02-06 23:39
I can confirm that adding ```root.setCached(true);``` on line 1734 of GrailsDomainBinder does fix the issue and caching is working again.

@puneetbehl You got this or do you still want a PR?

**Comment by longwa** [comment] 2020-02-06 23:39
This is a pretty huge performance hit so it would be pretty good to get it in the next release if at all possible.

**Comment by graemerocher** [comment] 2020-02-07 07:48
I thought this was fixed by https://github.com/grails/gorm-hibernate5/pull/167

**Comment by longwa** [comment] 2020-02-07 13:41
Didn’t realize there was a PR already (usually GitHub shows it associated with the issue ticket). Also since the ticket was still open and just assigned to someone yesterday I assumed it was still unresolved. Sorry for the confusion.

**Closed** 2020-02-07 14:09 UTC
