### ISSUE TITLE
Composite id properties aren't available in JPA

### ISSUE THREAD

**Issue by felixscheinost** [grails/gorm-hibernate5#234] opened 2020-10-26 16:45 UTC
## Problem

Consider a domain class like this:

```groovy
class CompositeIdDomain implements Serializable {

  DomainOne domainOne
  DomainTwo domainTwo
  String otherProperty

  static constraints = {
    id composite:["domainOne", "domainTwo"]
  }
}
```

In this case `domainOne` and `domainTwo` aren't known to JPA as attributes while they can be queried using Hibernate directly.

Accessing those attributes yields a `IllegalArgumentException`:

```
Unable to locate Attribute  with the the given name [domainOne] on this ManagedType [composite.id.jpa.CompositeIdDomain]
java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [domainOne] on this ManagedType [composite.id.jpa.CompositeIdDomain]
	at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.checkNotNull(AbstractManagedType.java:147)
	at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:118)
	at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:43)
	at org.hibernate.query.criteria.internal.path.AbstractFromImpl.locateAttributeInternal(AbstractFromImpl.java:111)
	at org.hibernate.query.criteria.internal.path.AbstractPathImpl.locateAttribute(AbstractPathImpl.java:204)
	at org.hibernate.query.criteria.internal.path.AbstractPathImpl.get(AbstractPathImpl.java:177)
	at CompositeIdQuerySpec.$tt__$spock_feature_0_4(CompositeIdQuerySpec.groovy:92)
	at CompositeIdQuerySpec.test JPA query with condition on domainOne_closure5(CompositeIdQuerySpec.groovy)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at grails.gorm.transactions.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:68)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:65)
	at CompositeIdQuerySpec.test JPA query with condition on domainOne(CompositeIdQuerySpec.groovy)
```

The calling code looks like this:

```groovy
    def criteriaBuilder = sessionFactory.criteriaBuilder
    def criteriaQuery = criteriaBuilder.createQuery()
    def root = criteriaQuery.from(CompositeIdDomain)
    criteriaQuery.select(root)
    criteriaQuery.where(criteriaBuilder.equal(root.get("domainOne"), domainOne))
    def query = sessionFactory.currentSession.createQuery(criteriaQuery)
```

## Example project

I prepared an example project at: https://github.com/felixscheinost/composite-id-jpa

Please run the integration test `CompositeIdQuerySpec` to see the problem.

## Further information

I tried debugging the problem but didn't get very far yet.

I'm not sure what Hibernate mapping is generated by the given GORM mapping.

One lead I have is that the `identifier` isn't correctly made known to JPA because the code runs into this `FIXME`: https://github.com/hibernate/hibernate-orm/blob/37a77e695d72b6c6c8fd84b542b8b66b575abd05/hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java#L326

**Comment by felixscheinost** [comment] 2020-10-26 17:21
I tried to reproduce the problem using Hibernate only and created another example project: https://github.com/felixscheinost/composite-id-jpa-hibernate/blob/master/src/main/java/com/example/CompositeIdDomain.java

```java 
@Entity
public class CompositeIdDomain implements Serializable {
  @Id
  @ManyToOne(fetch = FetchType.LAZY)
  private DomainA domainA;

  @Id
  @ManyToOne(fetch = FetchType.LAZY)
  private DomainB domainB;

  @Column
  private String otherProperty;

  public CompositeIdDomain(DomainA domainA, DomainB domainB, String otherProperty) {
    this.domainA = domainA;
    this.domainB = domainB;
    this.otherProperty = otherProperty;
  }

  public CompositeIdDomain() {
  }
}
```

Here everything works as expected (see test in example project).

In the debugger I stepped into `MetadataContext` again and the difference is that the `PeristentEntity` has an `identifierMapper`

So the code runs into the `else if` a few lines above the `else`: https://github.com/hibernate/hibernate-orm/blob/37a77e695d72b6c6c8fd84b542b8b66b575abd05/hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java#L316

Is the solution to make the `Composite` available as an`identifierMapper` as well?

**Comment by jjelliott** [comment] 2020-10-26 21:51
Possibly a duplicate of one or both of these: #143 and https://github.com/grails/grails-data-mapping/issues/1351

**Comment by felixscheinost** [comment] 2020-10-27 05:54
Definitely seems like a dupe of [grails/grails-data-mapping#1351](https://github.com/grails/grails-data-mapping/issues/1351)

Not sure about the other one

**Comment by jjelliott** [comment] 2020-10-27 13:08
It's a different symptom, but I'm pretty sure it's all the same underlying issue, which is that the hibernate mappings for composite key domains are not created correctly.

**Closed** 2021-12-17 17:57 UTC
