### ISSUE TITLE
Where query produces QueryException: duplicate alias

### ISSUE THREAD

**Issue by kktec** [grails/gorm-hibernate5#122] opened 2019-01-21 20:34 UTC
A Where query that combines the use of 2 expressions using nested properties with an OR produces a "duplicate alias":
`        
String strainFilter = params.filters?.strain
       
 Plant.where {
            if (strainFilter) { 
             seed.strain.code == strainFilter || mother.seed.strain.code == strainFilter  }
 }
`
Either expression used alone works.

A Micronaut groovy app demonstrates the problem:
https://github.com/kktec/wh1

**Comment by puneetbehl** [comment] 2020-01-30 21:58
It seems to be duplicate of grails/grails-data-mapping#1267

**Closed** 2020-02-04 09:40 UTC
Labels: closed: duplicate

**Comment by snimavat** [comment] 2021-09-13 08:05
Would like to have this fix before i can upgrade to gorm 7.0.3
@puneetbehl is there a work around for this error, like setting alias manually etc
